#!/usr/bin/env bash
root=$1

tmp=$(mktemp -u)
mv $root $tmp

path=$(cat "$tmp/pwd")
pid=$(cat "$tmp/pid")
if pgrep zsh | grep -qx "$pid"; then
  echo "Ignoring $pid at $root since it's already running" 1>&2
else
  kitty -d "$path" --detach --title "zsh-restored-$pid" -- zsh -is source "$tmp/env"
fi
